---
ID: "4157ac21-49e2-4c52-877e-fd3fca282462"
Parent: "bf87a996-1191-4d2e-a45d-e7d04667e9a6"
Template: "bf87a996-1191-4d2e-a45d-e7d04667e9a6"
Path: /sitecore/templates/Helix Arch/Project/ScHelix/PageTypeTemplates/Article/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180816T133126Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
