---
ID: "87759828-9bed-46e2-af92-1dd787fdedfa"
Parent: "9d13b377-970b-41ad-ad02-8d84c844ef45"
Template: "b122e6c6-5ad8-4357-a77a-635834fc1035"
Path: /sitecore/content/Basic/CookBook/Cookbook/Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180602T095250Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "7023f224-7b10-4dfb-bf66-ee728f274acf"
      Hint: Logo
      Value: |
        <image mediaid="{094AED03-02E7-4868-80CB-19926661FB77}" />
    - ID: "725b95ac-89f7-4c61-9693-c4a8ae44ac46"
      Hint: Name
      Value: Cookbook
    - ID: "ec93784f-3d98-4e24-9d28-07c13046ff29"
      Hint: Company
      Value: Sitecore
    - ID: "fe1954a4-1079-4bb0-9840-76b935487a5e"
      Hint: Copyright Text
      Value: Copyrights reserved
